// Angular/accedex-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'accedex-app';
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" [href]="['']">{{ title }}</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!--li class="nav-item">
          <a class="nav-link active" aria-current="page" [href]="['']">Home</a>
        </li-->
        <li class="nav-item">
          <a class="nav-link" [href]="['pokedex']">Pokedex</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [href]="['evolutions']">Evolutions</a>
        </li>
      </ul>
      <div class="d-flex">
        <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search"
          [(ngModel)]="pokemonSearch">
        <a class="btn btn-outline-success" [routerLink]="['/pokemon', pokemonSearch]">Search</a>

        <a *ngIf="authService.isLoggedIn === true" class="btn btn-outline-info ms-5"
          [routerLink]="('/user')">Profile</a>
        <a *ngIf="authService.isLoggedIn === true" class="btn btn-outline-danger ms-1" href=""
          (click)="authService.SignOut()">SignOut</a>
      </div>
    </div>
  </div>
</nav>

<router-outlet></router-outlet>

// React/accedex-app/src/App.js
import './App.css';
import { Outlet, Link } from 'react-router-dom';

function App() {
  return (
    <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <Link class="navbar-brand" to="/">Accedex</Link>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            <li class="nav-item">
              <Link class="nav-link" to="/pokedex">Pokedex</Link> 
            </li>
            <li class="nav-item">
              <Link class="nav-link" to="/evolutions">Evolutions</Link> 
            </li>
          </ul>
          <div class="d-flex">
            <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" />
            <Link class="btn btn-outline-success" to={`/pokemon/1`} key={'1'}>Search</Link>

            {/* Solo mostrar si esta logeado */}
            <Link class="btn btn-outline-info ms-5" to="/profile">Profile</Link>
            <Link class="btn btn-outline-danger ms-1" to="/logout">SignOut</Link>
          </div>
        </div>
      </div>
      </nav>
      
      <Outlet />
    </div>
  );
}

export default App;
