// React/accedex-app/src/pages/pokemon.js
/* eslint-disable no-array-constructor */
import { Link, useParams } from "react-router-dom";
import React, { useState, useEffect } from "react";
import { urlBase, loadingComponent, messageErrorComponent } from '../services/consts';

function Pokemon() {
    const param = useParams().id;

    const [isLoading, setIsLoading] = useState(true);
    const [noPokemonFound, setNoPokemonFound] = useState(false);
    const [data, setData] = useState();

    useEffect(() => {
        fetch(`${urlBase}/pokemon/${param}`)
            .then((res) => res.json())
            .then((response) => {
                const moves = new Array();
                response.moves.forEach(move => moves.push(move.move.name));

                const types = new Array();
                response.types.forEach(type => types.push(type.type.name));

                const statsColors = ['bg-success', 'bg-danger', 'bg-warning', 'bg-danger', 'bg-warning', 'bg-info'];
                const stats = new Array();
                response.stats.forEach((stat, index) => stats.push(
                    { name: stat.stat.name, baseStat: stat.base_stat, color: statsColors[index] },
                ));

                const sprites = new Array();
                if (response.sprites.front_default) sprites.push({ name: 'front_default', sprite: response.sprites.front_default });
                if (response.sprites.back_default) sprites.push({ name: 'back_default', sprite: response.sprites.back_default });
                if (response.sprites.front_female) sprites.push({ name: 'front_female', sprite: response.sprites.front_female });
                if (response.sprites.back_female) sprites.push({ name: 'back_female', sprite: response.sprites.back_female });
                if (response.sprites.front_shiny) sprites.push({ name: 'front_shiny', sprite: response.sprites.front_shiny });
                if (response.sprites.back_shiny) sprites.push({ name: 'back_shiny', sprite: response.sprites.back_shiny });
                if (response.sprites.front_shiny_female) sprites.push({ name: 'front_shiny_female', sprite: response.sprites.front_shiny_female });
                if (response.sprites.back_shiny_female) sprites.push({ name: 'back_shiny_female', sprite: response.sprites.back_shiny_female });


                setData({
                    'id': response.id,
                    'name': response.name,
                    'height': response.height,
                    'weight': response.weight,
                    'baseExperience': response.base_experience,
                    'moves': moves,
                    'types': types,
                    'stats': stats,
                    'sprites': sprites
                });
                setIsLoading(false);
            })
            .catch(() => setNoPokemonFound(true));
    }, [param]);

    return (
        <>
            {isLoading && !noPokemonFound && loadingComponent}

            {noPokemonFound && messageErrorComponent(`No pokemon found: ${param}`)}

            {!isLoading && (
                <>
                    <div key={data.id} className="page-pokemon">
                        <div className="container my-5">

                            <div className="row">
                                <div className="col">
                                    <h1 className="font-weight-bold"><b>#{data.id}</b></h1>
                                </div>

                                <div className="col d-flex flex-row-reverse">
                                    <button className="btn btn-outline-primary"><i className="bi bi-heart-fill"></i></button>

                                    <button className="btn btn-outline-danger"><i className="bi bi-heart-fill"></i></button>
                                </div>
                            </div>

                            <div className="d-flex py-3">
                                <div className="p-2">
                                    <Link className={`btn btn-primary ${(data.id - 1) ? '' : 'disabled'}`} to={`/pokemon/${data.id - 1}`} onClick={() => { setIsLoading(true) }}><i className="bi bi-arrow-left"></i> Back</Link>
                                </div>

                                <div className="p-2">
                                    <Link className="btn btn-primary" to={`/pokemon/${data.id + 1}`}>Next <i className="bi bi-arrow-right" onClick={() => { setIsLoading(true) }}></i></Link>
                                </div>
                            </div>

                            <div className="container">
                                <div className="row py-4">
                                    <div className="col-12 col-lg-4 bg-white mb-3 rounded box-shadow d-flex flex-column justify-content-center">
                                        <span className="mr-3 text-center">
                                            {/* carousel imgs */}
                                            <img className="d-block w-100" src={data.sprites[0].sprite} alt={data.sprites[0].name}></img>

                                            <h2 className="mt-4 pb-3 text-capitalize">
                                                <span className="font-weight-bold"><b>{data.name}</b></span>
                                            </h2>
                                        </span>
                                    </div>

                                    <div className="col-12 col-lg-8 h-100">
                                        <div className="pl-4 bg-white rounded box-shadow p-5">
                                            <p className="font-weight-bold"><b>Types:</b> </p>
                                            {
                                                data.types.map((type, index) => (
                                                    <span key={`type-${index}`} className={type + ' color-white info-span p-1 px-5'}>
                                                        {type}
                                                    </span>
                                                ))
                                            }

                                            <p className="mt-2">
                                                <span className="font-weight-bold"><b>Height:</b> </span> {data.height + ' | '}
                                                <span className="font-weight-bold"><b>Weight:</b> </span> {data.weight}
                                            </p>

                                            <p>
                                                <span className="font-weight-bold"><b>Base experience:</b></span> {data.baseExperience}
                                            </p>
                                        </div>
                                    </div>

                                    <div className="row pt-4">
                                        <h2>Stats</h2>
                                        {
                                            data.stats.map((stat, index) => (
                                                <div key={`stat-${index}`} style={{ height: '35px' }}>
                                                    <div className={`progress-bar ${stat.color}`} style={{ width: stat.baseStat + '%', maxWidth: '100%' }} role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                                        <span className="text-uppercase">{stat.name + ' : '} <span className="font-weight-bold"><b>{stat.baseStat}</b></span></span>
                                                    </div>
                                                </div>
                                            ))
                                        }
                                    </div>

                                    <div style={{ marginTop: '30px' }} className="row pt-4 justify-content-center">
                                        <h2>Moves</h2>
                                        {
                                            data.moves.map((move, index) => (
                                                <span key={`move-${index}`} className={data.types[0] + ' color-white info-move me-2 mt-2 col-2'}>{move}</span>
                                            ))
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </>
            )}
        </>
    );
}

export default Pokemon;

// Angular/accedex-app/src/app/components/pokemon/pokemon.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Pokemon } from 'src/app/models/pokemon.model';
import { PokemonsService } from 'src/app/services/pokemons.service';

@Component({
  selector: 'app-pokemon',
  templateUrl: './pokemon.component.html',
  styleUrls: ['./pokemon.component.css']
})
export class PokemonComponent implements OnInit {

  private id: number;
  private name: string;
  pokemons: Pokemon[] = [];
  disabledPrevious: boolean = false;
  alert: boolean = false;
  alertMessage: string;
  alertColor: string;
  pokemonsAPI: PokemonsService;

  constructor(pokemonsAPI: PokemonsService, private router: Router, private route: ActivatedRoute) {
    this.pokemonsAPI = pokemonsAPI;
  }

  ngOnInit() {
    this.getData(0);
  }

  previous() {
    if (this.pokemons[0].getId() <= 1) {
      this.alertMessage = 'This is the first pokemon';
      this.alertColor = 'alert-warning';
      this.alert = true;
      return;
    }

    this.router.navigateByUrl(`/pokemon/${this.pokemons[0].getId() - 1}`);

    this.getData(this.pokemons[0].getId() - 1);
  }

  next() {
    this.router.navigateByUrl(`/pokemon/${this.pokemons[0].getId() + 1}`);

    this.getData(this.pokemons[0].getId() + 1);
  }

  private getData(change: number) {
    this.alert = false;
    this.pokemonsAPI.clearPokemons();

    if (change) {
      this.pokemonsAPI.getMoreDataPokemonById(change);
    } else {
      if (isNaN(this.route.snapshot.params['id'])) {
        this.name = this.route.snapshot.params['id'];

        this.pokemonsAPI.getPokemonByName(this.name.toLocaleLowerCase());
      } else {
        this.id = this.route.snapshot.params['id'];

        this.pokemonsAPI.getMoreDataPokemonById(this.id);
      }
    }

    this.pokemons = this.pokemonsAPI.getListPokemons();
  }
}

<div class="page-pokemon">

  <div *ngIf="pokemonsAPI.loadingData; else pokemon" class="container">
    <div class="my-5 row pt-5">
      <div style="display: flex; justify-content: center;" class="col">
        <circle-progress [percent]="95" [radius]="100" [outerStrokeWidth]="16" [innerStrokeWidth]="8"
          [outerStrokeColor]="'#78C000'" [innerStrokeColor]="'#C7E596'" [animation]="true" [animationDuration]="3000">
        </circle-progress>
      </div>
    </div>
  </div>

  <ng-template #pokemon>
    <div *ngIf="!pokemonsAPI.noDataFound; else noPokemonData" class="container my-5">
      <div *ngIf="alert" class="container">
        <app-alert mensaje="{{ alertMessage }}" color="{{ alertColor }}"></app-alert>
      </div>

      <div class="row">
        <h1><span class="font-weight-bold">#{{ pokemons[0].getId() }}</span></h1>
      </div>

      <div class="d-flex py-3">
        <div class="p-2">
          <button (click)="previous()" class="btn btn-primary" [disabled]="disabledPrevious"><i
              class="bi bi-arrow-left"></i> Back</button>
        </div>

        <div class="p-2">
          <button (click)="next()" class="btn btn-primary">Next <i class="bi bi-arrow-right"></i></button>
        </div>
      </div>

      <div class="container">
        <div class="row py-4">
          <div class="col-12 col-lg-4 bg-white mb-3 rounded box-shadow d-flex flex-column justify-content-center">
            <span class="mr-3 text-center">
              <mdb-carousel [class]="'alert-dark'" [isControls]="true" [animation]="'slide'" width="300" height="300">
                <mdb-carousel-item>
                  <img class="d-block w-100" src="{{ pokemons[0].getUrl() }}" alt="First slide">
                </mdb-carousel-item>
                <mdb-carousel-item *ngFor="let image of pokemons[0].getSprintes()">
                  <img class="d-block w-100" src="{{ image }}" alt="First slide">
                </mdb-carousel-item>
              </mdb-carousel>
              <h2 class="mt-4 pb-3 text-capitalize"><span class="font-weight-bold">{{ pokemons[0].getName() }}</span>
              </h2>
            </span>
          </div>

          <div class="col-12 col-lg-8" style="height: 100%">
            <div class="pl-4 bg-white rounded box-shadow p-5">
              <p>
                <span *ngFor="let type of pokemons[0].getTypes()"
                  style="background-color: {{ pokemons[0].getColorByType(type) }} ;" class="color-white info_span">{{
                  type
                  }}</span>
              </p>
              <p><span class="font-weight-bold">Height: </span> {{ pokemons[0].getHeight() + ' | '}} <span
                  class="font-weight-bold">Weight:</span> {{ pokemons[0].getWeight() }} </p>
              <p><span class="font-weight-bold">Abilities:</span> {{ pokemons[0].getAbilities() }}</p>
              <p><span class="font-weight-bold">Base experience:</span> {{ pokemons[0].getBaseExperience() }}</p>
            </div>
          </div>
        </div>

        <div class="row pt-4">
          <h2>Stats</h2>
          <div class="progress mt-3" style="height: 25px;" *ngFor="let stat of pokemons[0].getStats()">
            <div class="progress-bar" role="progressbar"
              style="width: {{ stat.getBaseStat() }}%; background-color: {{ pokemons[0].getColor() }};"
              aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
              <span class="text-uppercase">{{stat.getName() + ' : ' }} <span class="font-weight-bold">{{
                  stat.getBaseStat() }}</span></span>
            </div>
          </div>
        </div>
      </div>

      <div class="row pt-4 justify-content-center">
        <h2>Moves</h2>
        <span *ngFor="let move of pokemons[0].getMoves()" class="color-white info_move me-2 mt-2"
          style="background-color: {{ pokemons[0].getColor() }};">{{ move
          }}</span>
      </div>
    </div>

    <ng-template #noPokemonData>
      <div class="container my-5">
        <div class="alert alert-danger w-100" role="alert">No se ha encontrado el Pokémon</div>
      </div>
    </ng-template>
  </ng-template>
</div>
